version: '3.9'

services:
  node:
    image: dockercommands
    build:
      context: .
      dockerfile: node.dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - APP_VERSION=1.0
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_SERVER=mongodb
      - MONGO_DB=funWithDocker
    depends_on: 
      - mongodb
      
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - db:/data/db

volumes:
  db:

